export enum DocumentationActionTypes {
  UPDATE_DOCUMENTATION_MODEL = 'UPDATE_DOCUMENTATION_MODEL',

  RESET_DOCUMENTATION_STORE = 'RESET_DOCUMENTATION_STORE',

  CLEAR_STATE = 'CLEAR_STATE',

  SET_PRODUCT_TYPE = 'SET_PRODUCT_TYPE'
}
